"""Add datetime to observation table

Revision ID: 9f58cf267a53
Revises: 849f9bc980ab
Create Date: 2024-11-17 22:25:35.665171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f58cf267a53'
down_revision: Union[str, None] = '849f9bc980ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_observation', sa.Column('observation_datetime', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weather_observation', 'observation_datetime')
    # ### end Alembic commands ###
