"""Make station name explicity

Revision ID: bc513310bddc
Revises: 9f58cf267a53
Create Date: 2024-11-17 23:22:42.848334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc513310bddc'
down_revision: Union[str, None] = '9f58cf267a53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_station', sa.Column('station_name', sa.String(), nullable=False))
    op.drop_column('weather_station', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_station', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('weather_station', 'station_name')
    # ### end Alembic commands ###
